CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) NOT NULL,
    password varchar(500) NOT NULL,
    status varchar(20) NOT NULL
);

CREATE INDEX idx_username ON users (username);

CREATE TABLE IF NOT EXISTS operation(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type varchar(20) NOT NULL,
    cost NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS record(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    operation_id integer NOT NULL,
    user_id integer NOT NULL,
    amount NUMERIC NOT NULL,
    user_balance NUMERIC(10,2) NOT NULL,
    operation_response VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL,
    inactive boolean NOT NULL,
    FOREIGN KEY (operation_id) REFERENCES operation(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS wallet(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    balance NUMERIC(10,2) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Charge user table
INSERT INTO users(username, password, status) VALUES ('user1@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user2@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user3@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user4@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user5@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user6@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user7@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user8@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user9@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');
INSERT INTO users(username, password, status) VALUES ('user10@user.com', '$2a$10$rFXuhNxdgaaihLRJwjDs1uIwnzuQE95ovnNrOMERY4Db4szvCXJ1u', 'ACTIVE');

-- Charge Operation table
INSERT INTO operation(type, cost) VALUES ('ADDITION', 30.0);
INSERT INTO operation(type, cost) VALUES ('SUBTRACTION', 40.0);
INSERT INTO operation(type, cost) VALUES ('MULTIPLICATION', 85.50);
INSERT INTO operation(type, cost) VALUES ('DIVISION', 100.0);
INSERT INTO operation(type, cost) VALUES ('SQUARE_ROOT', 150.0);
INSERT INTO operation(type, cost) VALUES ('RANDOM_STRING', 235.35);

-- Charge wallet table
INSERT INTO wallet(user_id, balance) VALUES (1, 1000.0);
INSERT INTO wallet(user_id, balance) VALUES (2, 500.0);
INSERT INTO wallet(user_id, balance) VALUES (3, 0.0);
INSERT INTO wallet(user_id, balance) VALUES (4, 10000.0);
INSERT INTO wallet(user_id, balance) VALUES (5, 2000.0);
INSERT INTO wallet(user_id, balance) VALUES (6, 5000.0);
INSERT INTO wallet(user_id, balance) VALUES (7, 8000.0);
INSERT INTO wallet(user_id, balance) VALUES (8, 15000.0);
INSERT INTO wallet(user_id, balance) VALUES (9, 3000.0);
INSERT INTO wallet(user_id, balance) VALUES (10, 2000.0);